### ISSUE TITLE
Not filed message

### ISSUE THREAD

**Issue by Natashkinsasha** [dbck/docker-mailtrap#2]
![image](https://user-images.githubusercontent.com/14879548/166838268-b2d840ab-bb02-4234-ace0-5c399a649e19.png)
![image](https://user-images.githubusercontent.com/14879548/166838293-ceccd6b6-f2e7-4750-8901-3468f1bb1d95.png)

**Comment by dbck** [comment]
@Natashkinsasha should be fixed in v1.0.1 of the container image.
